# Generated by Django 4.2.5 on 2023-09-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='entry.lib_user'),
        ),
    ]
