# Generated by Django 4.2.5 on 2023-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=60, null=True)),
                ('book_id', models.CharField(blank=True, max_length=60, null=True)),
                ('date_take', models.DateField(blank=True, null=True)),
                ('date_return', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
